<a href="https://colab.research.google.com/github/samiya-jabbar/my_deep_learning_assignments_AI_course_PIAIC/blob/main/Ionosphere_Data_Problem_PIAIC88719.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
data = pd.read_csv('./drive/MyDrive/ionosphere_data.csv')
data

     feature1  feature2  feature3  ...  feature33  feature34  label
0           1         0   0.99539  ...    0.18641   -0.45300      g
1           1         0   1.00000  ...   -0.13738   -0.02447      b
2           1         0   1.00000  ...    0.56045   -0.38238      g
3           1         0   1.00000  ...   -0.32382    1.00000      b
4           1         0   1.00000  ...   -0.04608   -0.65697      g
..        ...       ...       ...  ...        ...        ...    ...
346         1         0   0.83508  ...    0.90546   -0.04307      g
347         1         0   0.95113  ...    0.91483    0.04712      g
348         1         0   0.94701  ...    0.92697   -0.00577      g
349         1         0   0.90608  ...    0.87403   -0.16243      g
350         1         0   0.84710  ...    0.85764   -0.06151      g

[351 rows x 35 columns]

In [22]:
df.shape

(351, 35)

In [26]:
data.describe().T

           count      mean       std  min       25%      50%       75%  max
feature1   351.0  0.891738  0.311155  0.0  1.000000  1.00000  1.000000  1.0
feature2   351.0  0.000000  0.000000  0.0  0.000000  0.00000  0.000000  0.0
feature3   351.0  0.641342  0.497708 -1.0  0.472135  0.87111  1.000000  1.0
feature4   351.0  0.044372  0.441435 -1.0 -0.064735  0.01631  0.194185  1.0
feature5   351.0  0.601068  0.519862 -1.0  0.412660  0.80920  1.000000  1.0
feature6   351.0  0.115889  0.460810 -1.0 -0.024795  0.02280  0.334655  1.0
feature7   351.0  0.550095  0.492654 -1.0  0.211310  0.72873  0.969240  1.0
feature8   351.0  0.119360  0.520750 -1.0 -0.054840  0.01471  0.445675  1.0
feature9   351.0  0.511848  0.507066 -1.0  0.087110  0.68421  0.953240  1.0
feature10  351.0  0.181345  0.483851 -1.0 -0.048075  0.01829  0.534195  1.0
feature11  351.0  0.476183  0.563496 -1.0  0.021120  0.66798  0.957895  1.0
feature12  351.0  0.155040  0.494817 -1.0 -0.065265  0.02825  0.482375  1.0
feature13  351.0  0.400801  0.622186 -1.0  0.000000  0.64407  0.955505  1.0
feature14  351.0  0.093414  0.494873 -1.0 -0.073725  0.03027  0.374860  1.0
feature15  351.0  0.344159  0.652828 -1.0  0.000000  0.60194  0.919330  1.0
feature16  351.0  0.071132  0.458371 -1.0 -0.081705  0.00000  0.308975  1.0
feature17  351.0  0.381949  0.618020 -1.0  0.000000  0.59091  0.935705  1.0
feature18  351.0 -0.003617  0.496762 -1.0 -0.225690  0.00000  0.195285  1.0
feature19  351.0  0.359390  0.626267 -1.0  0.000000  0.57619  0.899265  1.0
feature20  351.0 -0.024025  0.519076 -1.0 -0.234670  0.00000  0.134370  1.0
feature21  351.0  0.336695  0.609828 -1.0  0.000000  0.49909  0.894865  1.0
feature22  351.0  0.008296  0.518166 -1.0 -0.243870  0.00000  0.188760  1.0
feature23  351.0  0.362475  0.603767 -1.0  0.000000  0.53176  0.911235  1.0
feature24  351.0 -0.057406  0.527456 -1.0 -0.366885  0.00000  0.164630  1.0
feature25  351.0  0.396135  0.578451 -1.0  0.000000  0.55389  0.905240  1.0
feature26  351.0 -0.071187  0.508495 -1.0 -0.332390 -0.01505  0.156765  1.0
feature27  351.0  0.541641  0.516205 -1.0  0.286435  0.70824  0.999945  1.0
feature28  351.0 -0.069538  0.550025 -1.0 -0.443165 -0.01769  0.153535  1.0
feature29  351.0  0.378445  0.575886 -1.0  0.000000  0.49664  0.883465  1.0
feature30  351.0 -0.027907  0.507974 -1.0 -0.236885  0.00000  0.154075  1.0
feature31  351.0  0.352514  0.571483 -1.0  0.000000  0.44277  0.857620  1.0
feature32  351.0 -0.003794  0.513574 -1.0 -0.242595  0.00000  0.200120  1.0
feature33  351.0  0.349364  0.522663 -1.0  0.000000  0.40956  0.813765  1.0
feature34  351.0  0.014480  0.468337 -1.0 -0.165350  0.00000  0.171660  1.0

In [33]:
for feature in data:
    print(feature)
    print(len(data[feature].unique()))

feature1
2
feature6
259
feature7
231
feature8
260
feature9
244
feature10
267
feature11
246
feature12
269
feature13
238
feature14
266
feature15
234
feature16
270
feature17
254
feature18
280
feature19
254
feature20
266
feature21
248
feature22
265
feature23
248
feature24
264
feature25
256
feature26
273
feature27
256
feature28
281
feature29
244
feature30
266
feature31
243
feature32
263
feature33
245
feature34
263
label
2

In [28]:
data['feature2'].unique()

array([0])

In [ ]:
data.drop(data.columns[1], inplace=True, axis=1)
df.head()

In [ ]:
data.describe()

In [ ]:
data.isnull().sum()

In [39]:
data['label'] = [1 if lbl == 'g' else 0 for lbl in data['label']]

In [40]:
train_data = data.sample(frac= 0.6, random_state=125)
test_data = data.drop(train_data.index)

In [42]:
train_label = train_data.iloc[:,-1]
train_data = train_data.iloc[:,0:-1]
test_label = test_data.iloc[:,-1]
test_data = test_data.iloc[:,0:-1]

In [43]:
train_data.head()

     feature1  feature6  feature7  ...  feature31  feature32  feature33
270         1  -0.00482   0.96683  ...    0.92774   -0.03464    0.92226
116         1   0.04918   0.57377  ...    0.27869   -0.44262    0.49180
135         1   0.37500   0.74265  ...   -0.44118   -0.50735   -0.28676
91          1  -0.80553  -0.08961  ...   -0.21354   -0.78170   -0.18494
100         1   0.00000   0.77941  ...    1.00000   -1.00000    0.00000

[5 rows x 29 columns]

In [44]:
train_label

270   -0.03673
116   -0.06557
135   -0.56618
91    -0.59867
100    0.00000
        ...
213    0.00000
161   -0.09186
141    0.00809
59     0.00000
113   -0.53319
Name: feature34, Length: 211, dtype: float64